GET http://localhost:3002/authv2/session
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ODExY2E5ZS0zMjMwLTQxZGUtYjMyZS0xOTZkOTQ5ZTZiZDEiLCJ1c2VybmFtZSI6ImV4YW1wbGVVc2VyIiwiaWF0IjoxNzMzNTkzMjI0LCJleHAiOjE3MzM2Nzk2MjR9.s20w4qjTG52gcEFNKH2WA7jjXUvHhrWVqyVuIACrO_E