GET http://localhost:3002/auth/session
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZDU4NzUxZC0wYTQ2LTRlOTctOTQyYS01MjlmNWE1ZTlhZDciLCJ1c2VybmFtZSI6InBhdHJ5a2RvZSIsImlhdCI6MTczMzU4MjE0NywiZXhwIjoxNzMzNjY4NTQ3fQ.6pfs3bTTM9q5Ykdbbq9wq1Bgbp95kLbDId4itzgqB-c 